name: Deploy Staging
on:
  push:
    branches:
      - development

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      annotation-ui: ${{ steps.filter.outputs.annotation-ui }}
      ogbv-ml-rest: ${{ steps.filter.outputs.ogbv-ml-rest }}
      browser-extension-server: ${{ steps.filter.outputs.browser-extension-server }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            annotation-ui:
                - 'annotators/backend/**/*'
                - 'annotators/annotation-ui/**/*'
            ogbv-ml-rest:
                - 'ogbv-ml-rest/**/*'
            browser-extension-server:
                - 'browser-extension/api-server/**/*'

  annotation-ui:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.annotation-ui == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          cd annotators/annotation-ui
          npm install
          npm run build

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/ogbv_annotator
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: annotators/backend/

      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          command: set image --record deployment/annotation-ui-staging annotation-ui-staging=tattletech/ogbv_annotator:${{ steps.vars.outputs.sha_short }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/annotation-ui-staging

  ogbv-ml-rest:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.ogbv-ml-rest == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: development

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and Push to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/ogbv-ml-rest
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: ogbv-ml-rest

      # - name: deploy to cluster
      #   uses: steebchen/kubectl@v2.0.0
      #   with: # defaults to latest kubectl binary version
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     command: set image --record deployment/ogbv-ml-rest ogbv-ml-rest=tattletech/ogbv-ml-rest:${{ steps.vars.outputs.sha_short }}
      # - name: verify deployment
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     version: v1.21.0 # specify kubectl binary version explicitly
      #     command: rollout status deployment/ogbv-ml-rest

  browser-extension-server:
    runs-on: "ubuntu-latest"
    needs: "changes"
    if: ${{ needs.changes.outputs.browser-extension-server == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "finish"
